version: 0.1

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Resume_Jorge_Rodriguez.pdf
    - styles/main.css
    - images/*
